// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDy-pIWXiV3mngy464vmRgmVNm0-3Tx2A',
    appId: '1:339426936524:web:f6ebaf5de4c8d2c1c72469',
    messagingSenderId: '339426936524',
    projectId: 'beatrizmartinez-9b',
    authDomain: 'beatrizmartinez-9b.firebaseapp.com',
    storageBucket: 'beatrizmartinez-9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_g2VLTTcjjdbG4EsMN3iReinXUqJVPo',
    appId: '1:339426936524:android:ad23e97685f91739c72469',
    messagingSenderId: '339426936524',
    projectId: 'beatrizmartinez-9b',
    storageBucket: 'beatrizmartinez-9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaMQf8ciLvChE51z7UUxilyurpGLwh5WM',
    appId: '1:339426936524:ios:ce8294f68cfe66cac72469',
    messagingSenderId: '339426936524',
    projectId: 'beatrizmartinez-9b',
    storageBucket: 'beatrizmartinez-9b.appspot.com',
    iosBundleId: 'com.example.firebaseApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaMQf8ciLvChE51z7UUxilyurpGLwh5WM',
    appId: '1:339426936524:ios:ce8294f68cfe66cac72469',
    messagingSenderId: '339426936524',
    projectId: 'beatrizmartinez-9b',
    storageBucket: 'beatrizmartinez-9b.appspot.com',
    iosBundleId: 'com.example.firebaseApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDy-pIWXiV3mngy464vmRgmVNm0-3Tx2A',
    appId: '1:339426936524:web:032b779fa5d31147c72469',
    messagingSenderId: '339426936524',
    projectId: 'beatrizmartinez-9b',
    authDomain: 'beatrizmartinez-9b.firebaseapp.com',
    storageBucket: 'beatrizmartinez-9b.appspot.com',
  );
}
